# SPDX-FileCopyrightText: 2025 EBFM Authors
#
# SPDX-License-Identifier: BSD-3-Clause

name: Build and test
on:
  - push
  - pull_request

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EBFM repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
      - name: Create virtual environment and install EBFM
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          pip3 install .
      - name: Check Git version
        run: |
          source .venv/bin/activate
          git --version
      - name: Check EBFM version
        run: |
          source .venv/bin/activate
          ebfm --version
      - name: Run example
        run: |
          source .venv/bin/activate
          ebfm --matlab-mesh examples/dem_and_mask.mat

  build-and-test-python-3-9-9:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout EBFM repository
        uses: actions/checkout@v3
      - name: Set up Python 3.9.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.9'
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
      - name: Create virtual environment and install EBFM
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          pip3 install .
      - name: Check Git version
        run: |
          source .venv/bin/activate
          git --version
      - name: Check EBFM version
        run: |
          source .venv/bin/activate
          ebfm --version
      - name: Run example
        run: |
          source .venv/bin/activate
          ebfm --matlab-mesh examples/dem_and_mask.mat